language: node_js

node_js:
  - stable

install:
  - npm install

jobs:
  include:
    - stage: test
      script:
        - npm run test
    - stage: release
      deploy:
        provider: script
        skip_cleanup: true
        on:
          branch: next
        script:
          - npx semantic-release